[project]
name = "sdl"
version = "1.0.1"
description = "SDL bindings for Mire (SDL2 + SDL3)"
entry = "code/mod.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0

[paths]
sources = "code"
tests = "tests"
output = "bin"
cache = "bin/.cache"

[exports]
sdl3 = "code/sdl3"
sdl2 = "code/sdl2"
